#!/usr/bin/python

def dec2hex(n):
   return "%02X" % n

def main():
   
   input = raw_input("DIS septuple: ")
   
   tuples = input.split(':')
   
   if len(tuples) != 7:
      print("Invalid setuple.")
      main() 
   
   hex = " Hex setuple: "
   
   hex += dec2hex (int(tuples[0])) + " "
   hex += dec2hex (int(tuples[1])) + " "
   hex += "00 " + dec2hex (int(tuples[2])) + " "
   hex += dec2hex (int(tuples[3])) + " "
   hex += dec2hex (int(tuples[4])) + " "
   hex += dec2hex (int(tuples[5])) + " "
   hex += dec2hex (int(tuples[6])) + " "

   hex = hex[0:len(hex)-1]

   print hex

   main()

main()

