#!/bin/bash

# Prepare bin directory
mkdir -p bin
rm -rf bin/*

# Clean and compile source
cd src
find . -name "*.class" | xargs rm > /dev/null 2>&1
javac -d ../bin orbisoftware/aquarius/pdu_sequencer/Desktop.java
cd ..

# Create jar file
cd bin
echo "Main-Class: orbisoftware.aquarius.pdu_sequencer.Desktop" > tmp
jar cmf tmp ../pdu_generator.jar orbisoftware 
rm tmp
cd ..

echo
echo "pdu_generator.jar created"
echo "usage: java -jar pdu_generator.jar"
